apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  annotations:
    image.fluxcd.io/automated: "true"
    image.fluxcd.io/tag: latest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: ghcr.io/atbender/blog:latest
        ports:
        - containerPort: 80 