apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: ghcr.io/atbender/blog:sha-9f1a78f
        command: ["hugo"]
        args: ["server", "--bind", "0.0.0.0", "--disableFastRender", "--noHTTPCache"]
        ports:
        - containerPort: 1313
        env:
        - name: HUGO_WATCH
          value: "true"
        - name: HUGO_BIND
          value: "0.0.0.0"
        - name: HUGO_PORT
          value: "1313" 