apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog
spec:
  imageRepositoryRef:
    name: blog
  policy:
    alphabetical:
      order: asc
      filterTags:
        pattern: '^latest$'