apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog
spec:
  imageRepositoryRef:
    name: blog
  policy:
    semver:
      range: '>=0.0.0'
      filterTags:
        pattern: '^sha-[a-f0-9]+$'
        extract: '$0'