apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;

        # Handle redirects from localhost:1313
        location / {
            sub_filter 'http://localhost:1313' 'https://blog.xandilabs.uk';
            sub_filter_once off;
            sub_filter_types text/html;
            proxy_pass http://localhost:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    } 