apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:2r01dYOpJ1B4c2bMe9AbZf9jAEZKDDAPj16X8HZWwpgUVecxrMK4xXMFJq9WXtUIRBlMk6hw56s6gZV8rc29hCsdQlFvA9MeQdFvW3LKzJdTXx9Hv6mG501R91MB+hYSSCvq2XvQUg3ct0UQrMml2lHkbXQ1eZOEZG8S2giQI1/B/MDQDSqesh/EnCFU+4vp8/kVknrUmMMi1ce0NWXbwLFtuNPTs0Fq8II4WYK5yjp2gE6tSDemNXwr6PFXfrPWqgDau8AHG9XJ7KlaATUf0k2PkQ7twpnC/RZ2t3hiKgvNq/xjRk8hSbyWQA0=,iv:L0QzI3hsvN5BbQZ1ZOOjcdUaQMsHkPMcgmWVrtvpCEI=,tag:QROGqkl50l6ONYao+WiNxw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gynmj9vwh8g2kmlgn0h7jhkkhjn92eyscjs6x8zysfd7jv34d4dqmk3n25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYjJ6VHo1SkU1ZnpuMXNh
            VEpkYUprWi9yd0t6dmtzZDZYc2VaYmxHV1JFCjhTNkF0UlV2N0gzdlhOajU1cWxM
            VWphQzQ3VU1NeGVyWmx5WEx3SUhLUlkKLS0tIExneTJxUnlmTU1WZlU2azdiWGhl
            Z1hZRjZNeEFYYkV4dGRaS2lPb25uQXMKuOaD3no/WDdrlf9V+HuO6BKTnYkRjuEm
            9WiR/7nOJGgvzY6/CJBYbrhc1udnSsMUP+yAvP82QMrpLjINYUHxTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T11:07:48Z"
    mac: ENC[AES256_GCM,data:lFpS8GZrQTNCgXxrVwQUUfCIjz0bxCZXALMM9WU/958PmLfI735CZ1mXPvIDoLrHGMKzb18ZOZT7AeLRRaungM3EufKuJzz2P32iwX1kIJv4N/xNo0+Z56M2FaQXJ8LCJUpFPGm5fM97zToTlbpmHaagp00Pw25BTGee7RZFXZI=,iv:eSIV19ynO718lr+e3iwr9eS7Hgu/JNRRS2OpowkoVCQ=,tag:bKDm4jvrC4xZ8ifsUy8uaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
